name: Publish hello world image
on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gonigo/dome9
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    name: Deploy to amazon ecs
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition dome9-hw --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: dome9-hw
          image: docker.io/gonigo/dome9:sha-${{ steps.vars.outputs.sha_short }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: helloworld-dev
          cluster: dome9-dev
          wait-for-service-stability: true
